### PR TITLE
Handle gRPC connection error properly

### PR DESCRIPTION
**Pull request by RussellLuo**
Fixed issue #159.

### CODE REVIEW

**Comment by rogeralsing** [comment]
There are things we should consider here too.
If the Connect fails for whatever reason, the EndpointWriter will be in an invalid state.
It will be restarted if anyone tries to send something via it.
But maybe there are some design ideas we can get out of it.
e.g should the EndpointWriter change state into Invalid?
Should it stop itself / Ask the EndpointManager to remove it from it's internal routing table?

Thoughts?

**Comment by RussellLuo** [comment]
After taking a quick look at the related code, I think maybe we need:
1. send a message, much similar to the message `EndpointTerminatedEvent` or something new named `EndpointUnavailableEvent`, to indicate the endpointWriter is broken
2. then, stop the endpointWriter itself

In order to get the above steps to work, maybe we should also change the [`EndpointTerminatedEvent ` handler in endpointWriter](https://github.com/AsynkronIT/protoactor-go/blob/dev/remote/endpoint_manager.go#L53-L56) to remove broken endpoint from the internal `state.connections`, after which a new endpoint can be spawned when necessary.

**Comment by alex023** [comment]
@RussellLuo `EndpointUnavailableEvent` is good choice

**Comment by rogeralsing** [comment]
I will merge this as it fixes the direct problem at hand, and we can discuss a more complete solution as a separate issue

**Pull request merged**
