### PR TITLE
fix roundrobin_router when access the maximum of int32 will produce a…

### PR DESCRIPTION
**Pull request by qgymje**
… minus index value which will cause panic

### CODE REVIEW

**Comment by qgymje** [comment]
maybe "let it crash" ?

**Comment by alex023** [comment]
The method [roundRobinRoutee]just used by [RouteMessage],and input param ```index *int32```is only ```&state.index``` which default minimum value is 0. 
Because unique creation method is [[source code]](https://github.com/AsynkronIT/protoactor-go/blob/dev/router/roundrobin_router.go#L45-#L47)：
```golang
func (config *roundRobinPoolRouter) CreateRouterState() Interface {
	return &roundRobinState{}
}
```
So，i think this modification is unnecessary at present .

**Comment by cpx86** [comment]
Nice catch!

@alex023 The `index` field is incremented each time a message is sent. So if `index` is int32 max, `i` will overflow to a negative (int32 min), which after modulus becomes a negative index in the array access :)

**Comment by qgymje** [comment]
@alex023 It's not about the minimum value of state.index, it's about the maximum value of state.index

**Comment by alex023** [comment]
Oh, I did not think about that。v_v

**Pull request merged**
