### PR TITLE
Complete the sender field of deadletters object. #60

### PR DESCRIPTION
**Pull request by killgxlin**

### CODE REVIEW

**Comment by rogeralsing** [comment]
We need a signed CLA before merging, thanks

**Comment by killgxlin** [comment]
oh, sorry. and i has signed my email address? do you need me to make a pr again?

**Comment by rogeralsing** [comment]
Probably just some hickup on the bot, I see that you have signed it. merging

**Comment by rogeralsing** [comment]
Thanks!

**Pull request merged**
